### ISSUE TITLE
Fitur Play Error

### ISSUE THREAD

**Issue by tukangit** [Urbaee/whatsapp-bot2#15]
Fitur Play Error, File Yang dikirim berbentuk .bin ( Bukan Voice Note / Mp3 ), 
Di Windows Sudah Terinstall FFMPEG, dan di bagian env sudah di edit. ( Tetep Error )
Tapi Ketika Di Jalankan Di Ubuntu berjalan normal ( file yang dikirim berbentuk vn ).

Biar Bisa Jalan Di VPS Windows Edit Lokasi FFMPEG di sc nya dibagian mana ya bang ? :(

**Comment by Urbaee** [comment]
> Fitur Play Error, File Yang dikirim berbentuk .bin ( Bukan Voice Note / Mp3 ), 
> Di Windows Sudah Terinstall FFMPEG, dan di bagian env sudah di edit. ( Tetep Error )
> Tapi Ketika Di Jalankan Di Ubuntu berjalan normal ( file yang dikirim berbentuk vn ).
> 
> Biar Bisa Jalan Di VPS Windows Edit Lokasi FFMPEG di sc nya dibagian mana ya bang ? :(

Iya nanti dibenerin

**Comment by Urbaee** [comment]
> Fitur Play Error, File Yang dikirim berbentuk .bin ( Bukan Voice Note / Mp3 ),
> Di Windows Sudah Terinstall FFMPEG, dan di bagian env sudah di edit. ( Tetep Error )
> Tapi Ketika Di Jalankan Di Ubuntu berjalan normal ( file yang dikirim berbentuk vn ).
> 
> Biar Bisa Jalan Di VPS Windows Edit Lokasi FFMPEG di sc nya dibagian mana ya bang ? :(

done fixed
