### ISSUE TITLE
#ttp dan #sticker

### ISSUE THREAD

**Issue by wahyucraft2** [Urbaee/whatsapp-bot2#18]
kak ini #ttp sama #sticker nya gabisa.
ERROR 404 mulu

[EXEC] 31/01/21 21:57:46 ttp [0] from Y in SHADOW DARK BOT
Request failed with status code 404

**Comment by Urbaee** [comment]
> kak ini #ttp sama #sticker nya gabisa.
> ERROR 404 mulu
> 
> [EXEC] 31/01/21 21:57:46 ttp [0] from Y in SHADOW DARK BOT
> Request failed with status code 404

Solusi :
run di cmd atau terminal ketik ini 
npm i --save @open-wa/wa-automate@3.2.0

**Comment by wahyucraft2** [comment]
makasih kak solusinya

**Comment by wahyucraft2** [comment]
Udah bisa kak. makasih banyak

**Comment by wahyucraft2** [comment]
:)
