### ISSUE TITLE
Eror IG download

### ISSUE THREAD

**Issue by agusydk3** [Urbaee/whatsapp-bot2#9]

**Comment by thoriqazzikra** [comment]
Gada api key nya

**Comment by thoriqazzikra** [comment]
> _No description provided._
Nih buka di settings trus cari keyword keepsave

Nih gua kasi apikeynya keepsave
Fj40gInAUVRvNK16phVoT9KzNg6D4vigTZQZlVLchaClRr

**Comment by agusydk3** [comment]
sama aja sob
